version: '3.8'
services:
  frontend:
    build: 
      context: todo-frontend_node
    image: frontend_image
    ports: 
      - "8080:8080"
    links:
      - backend
    environment:
      - BACKEND_HOST=backend:8100
  backend:
    build: ./todo-backend
    ports: 
      - "8100:8100"
    environment:
      - DATABASE_NAME=todo-db
      - DATABASE_USER=df6182cb-2213-44a7-84dd-768d5db98d76-bluemix
      - DATABASE_PASSWORD=80169c1eef1a177f3c125757f3bc50aa4f08db591462ba722a894baf41674f2f
      - DATABASE_HOST=df6182cb-2213-44a7-84dd-768d5db98d76-bluemix.cloudantnosqldb.appdomain.cloud
      - PORT=8100

    
