apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-backend
  name: todo-backend
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: todo-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - env:
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              key: DATABASE_HOST
              name: db-secret
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              key: DATABASE_NAME
              name: db-secret
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DATABASE_PASSWORD
              name: db-secret
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              key: DATABASE_USER
              name: db-secret
        - name: PORT
          valueFrom:
            configMapKeyRef:
              key: PORT
              name: backend-cm
        image: us.icr.io/summer-lab/todo-backend:latest
        imagePullPolicy: Always
        name: todo-backend
        ports:
        - containerPort: 8100
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
