apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: todo-backend
  name: todo-backend
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8100
  selector:
    app: todo-backend
status:
  loadBalancer: {}
